# Generated by Django 3.2.19 on 2023-09-02 02:34

import articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(validators=[articles.validators.textfield_not_empty]),
        ),
    ]
