# Generated by Django 3.2.19 on 2023-09-02 16:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1686206490/placeholder', max_length=255, verbose_name='image'),
        ),
    ]
