# Generated by Django 3.2.19 on 2023-06-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Baby & Kids', 'Baby & Kids'), ('Body', 'Body'), ('Face', 'Face'), ('Lips', 'Lips'), ('After Sun', 'After Sun')], max_length=30),
        ),
        migrations.AlterField(
            model_name='type',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Lotion', 'Lotion'), ('Spray', 'Spray'), ('Stick', 'Stick'), ('Roll-On', 'Roll-On')], max_length=30),
        ),
    ]
