# Generated by Django 3.2.19 on 2023-06-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230608_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='display_name',
        ),
    ]
