# Generated by Django 3.2.19 on 2023-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230610_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('baby_kids', 'Baby & Kids'), ('body', 'Body'), ('face', 'Face'), ('lips', 'Lips'), ('after_sun', 'After Sun')], max_length=30),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('lotion', 'Lotion'), ('spray', 'Spray'), ('stick', 'Stick'), ('roll-on', 'Roll-On')], max_length=30),
        ),
    ]
