# Generated by Django 3.2.19 on 2023-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230610_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
