# Generated by Django 3.2.19 on 2023-06-28 20:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_brand_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1686206490/placeholder', max_length=255, verbose_name='image'),
        ),
    ]
