# Generated by Django 3.2.19 on 2023-06-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Lotion', 'Lotion'), ('Spray', 'Spray'), ('Stick', 'Stick'), ('Roll-On', 'Roll-On')], max_length=30),
        ),
    ]
